package PallindromeStringApp;


/**
* PallindromeStringApp/PallindromeString.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PallindromeString.idl
* Friday, 9 May, 2025 8:06:47 PM IST
*/

public interface PallindromeString extends PallindromeStringOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PallindromeString
