package PallindromeStringApp;


/**
* PallindromeStringApp/PallindromeStringOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PallindromeString.idl
* Friday, 9 May, 2025 8:06:47 PM IST
*/

public interface PallindromeStringOperations 
{
  String checkPalindrome (String input);
} // interface PallindromeStringOperations
